server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/admin/users/**

            - id: productos
              uri: http://localhost:8082
              predicates:
                - Path=/api/productos/**

            - id: ordenes
              uri: http://localhost:8083
              predicates:
                - Path=/api/pedidos/**

            - id: direcciones
              uri: http://localhost:8085
              predicates:
                - Path=/api/direcciones/**

            - id: pagos
              uri: http://localhost:8086
              predicates:
                - Path=/api/pagos/**

            - id: envios
              uri: http://localhost:8087
              predicates:
                - Path=/api/envios/**

          globalcors:
            corsConfigurations:
              "[/**]":
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
          httpclient:
            connect-timeout: 10000
            response-timeout: 60s

management:
  endpoint:
    gateway:
      access: read-only
    web:
      exposure:
        include: "*"
