server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/admin/users/**
          filters:
            - StripPrefix=1

        - id: productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=1

        - id: ordenes
          uri: http://localhost:8083
          predicates:
            - Path=/api/pedidos/**
          filters:
            - StripPrefix=1

        - id: direcciones
          uri: http://localhost:8085
          predicates:
            - Path=/api/direcciones/**
          filters:
            - StripPrefix=1

        - id: pagos
          uri: http://localhost:8086
          predicates:
            - Path=/api/pagos/**
          filters:
            - StripPrefix=1

        - id: envios
          uri: http://localhost:8087
          predicates:
            - Path=/api/envios/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: ${app.cors.allowed-origins}
            allowedMethods: ${app.cors.allowed-methods}
            allowedHeaders: ${app.cors.allowed-headers}

      httpclient:
        connect-timeout: 10000
        response-timeout: 60s
