# marketplace-config/application.yml
# Config común heredada por todos los microservicios y el gateway
management:
  server:
    port: 9090          # puerto solo de gestión dentro del contenedor
    address: 127.0.0.1  # no se expone fuera del contenedor
  endpoints:
    web:
      exposure:
        # Incluye /actuator/gateway/routes para inspeccionar rutas del Gateway
        include: health,info,gateway,refresh,busrefresh
  endpoint:
    health:
      probes:
        enabled: true


# Spring Cloud Bus (Kafka) por defecto en local
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# CORS de demo reutilizable (el Gateway lo lee abajo vía placeholders si quieres)
app:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
