# --- Base (opcional): cosas compartidas por todos los perfiles
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,refresh,busrefresh
  endpoint:
    health:
      probes:
        enabled: true

app:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
---
# --- Perfil default (local)
spring:
  config:
    activate:
      on-profile: default
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
---
# --- Perfil docker (en contenedores)
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

management:
  server:
    port: 9090
    address: 127.0.0.1   # cámbialo a 0.0.0.0 si quieres acceder desde host/u otros contenedores
