server:
  port: 8081

spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true  # Formatea el SQL para mayor legibilidad
      database-platform: org.hibernate.dialect.PostgreSQLDialect


  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  # Configuración del token JWT
  jwt:
#    secret: ${JWT_SECRET}  # Se recomienda cargar desde variable por seguridad
    access-token:
      expiration-ms: 10800000  # Tiempo de expiración del access token (milisegundos)
    refresh-token:
      expiration-ms: 604800000  # Tiempo de expiración del refresh token (milisegundos)


