server:
  port: 8081

spring:
  datasource:
    # Default local; si exportas SPRING_DATASOURCE_URL, lo sobreescribe
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}   # <- secreto por ENV/Vault, aquí no
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_BINDER_LOG:TRACE}

jwt:
  secret: ${JWT_SECRET}                                   # <- secreto por ENV/Vault
  access-token:
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}     # 15 min por defecto
  refresh-token:
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000} # 7 días
