server:
  port: 8081

spring:
  datasource:
    # Default docker; también acepta override por SPRING_DATASOURCE_URL
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-postgres:5432/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG:INFO}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_BINDER_LOG:INFO}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
  refresh-token:
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}
