server:
  port: 8085

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/direccionesdb
#    username: postgres
#    password: Chuchoska387
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#jwt:
#  secret: MiSuperClaveSecretaParaJWT12345678901234567890


