server:
  port: 8089

spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
    consumer:
      auto-offset-reset: latest     # notificaciones => no reprocesar histórico
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "com.marketplace.app.*"
            use:
              type:
                headers: false   # usamos tipo por defecto vía factory Java
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  consumer-groups:
    pedido-enviado: notificacion-envio-group
    pedido-entregado: notificacion-entregado-group
    pedido-cancelado: notificacion-cancelado-group

clientes:
  pedidos: http://localhost:8083
  email: http://localhost:8089
  push: http://localhost:8089
#  token: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VySWQiOjEsInJvbGVzIjpbIkNPTVBSQURPUiIsIlZFTkRFRE9SIiwiQURNSU4iXSwiaWF0IjoxNzU3MDM2ODcwLCJleHAiOjE3NTcwNDA0NzB9.rUG95CVVUKqK67KOoWCp9oU7KWTms1fdBCRYFufDkdE"
