server:
  port: 8083

spring:
  datasource:
#    url: jdbc:mysql://localhost:3307/ordenesdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: Chuchoska387
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: '*'

  consumer-groups:
    pago-confirmado: ordenes-group-v2
    pedido-enviado: pedido-enviado-group-v2
    pedido-entregado: pedido-entregado-group-v2
    pedido-cancelado: pedido-cancelado-group-v2

logging:
  level:
    feign: DEBUG
    com.marketplace.app.ordenes.client: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org:
    springframework:
      kafka: INFO

jwt:
#  secret: MiSuperClaveSecretaParaJWT12345678901234567890
